
# OCaml sources (will be copied)
OCAML_SRC = $(HOME)/.opam/4.00.1/lib/ocaml-src

# Where the cross-compiler libraries are installed
W32_PREFIX = $(HOME)/.opam/4.00.1/i686-w64-mingw32

# Where the cross-compiler binaries are installed
W32_BINDIR = $(HOME)/.opam/4.00.1/bin
